FROM node:lts-alpine as builder

# RUN apk --no-cache add g++ make python2

WORKDIR /cmp-front-user

# Copy the rest of the application files
COPY . .

# install project dependencies
RUN rm -rf node_modules/ && rm -rf package-lock.json
RUN npm install --legacy-peer-deps

# Install Vite and its Vue plugin
RUN npm install vite@latest @vitejs/plugin-vue --save
RUN npm install --save-dev autoprefixer

# add `/cmp-front-user/node_modules/.bin` to $PATH
ENV PATH /cmp-front-user/node_modules/.bin:$PATH
ENV NODE_OPTIONS="--openssl-legacy-provider"

# Expose the port that the application will run on
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "dev"]