FROM node:19-alpine as builder

# RUN apk --no-cache add g++ make python2

WORKDIR /cmp-front-user

# add `/cmp-front-user/node_modules/.bin` to $PATH
ENV PATH /cmp-front-user/node_modules/.bin:$PATH
ENV NODE_OPTIONS="--openssl-legacy-provider"

# Copy the rest of the application files
COPY . .

# install project dependencies
RUN npm install -g npm@latest
RUN npm run install:clean

# Expose the port that the application will run on
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "dev"]