version: "3.9"
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/cmp-front-user
      - /cmp-front-user/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/nginx.staging.conf:/etc/nginx/conf.d/default.conf
      - ./data/certs/cloudminepro.crt:/etc/nginx/certs/cloudminepro.crt
      - ./data/certs/cloudminepro.key:/etc/nginx/certs/cloudminepro.key
      - static_volume:/cmp_api_python/static
      - media_volume:/cmp_api_python/media
    networks:
      - my_network

volumes:
  static_volume:
    external: true
  media_volume:
    external: true

networks:
  my_network:
    external: true
