version: "3.9"
services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/cmp-front-user
      - /cmp-front-user/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
